version: "3.9"
services:
  # Database for automated integrations tests
  db-it:
    image: "postgres:15.4-alpine3.18"
    container_name: "${COMPOSE_PROJECT_NAME}-db-it"
    hostname: db-it
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${DB_IT_USER}
      - POSTGRES_PASSWORD=${DB_IT_PASS}
      - POSTGRES_DB=${DB_IT_NAME}
    ports:
      - "${DB_IT_PORT}:5432"
    volumes:
      - db-it-data:/var/lib/postgresql/data
  keycloak-it:
    image: "jboss/keycloak:11.0.0"
    container_name: "${COMPOSE_PROJECT_NAME}-keycloak-it"
    hostname: keycloak-it
    restart: unless-stopped
    environment:
      - "KEYCLOAK_USER=admin"
      - "KEYCLOAK_PASSWORD=admin"
      - "DB_VENDOR=h2"
    ports:
      - "18080:8080"

volumes:
  db-it-data:
